FROM ubuntu:xenial

MAINTAINER esteve@apache.org

ENV NAO_HOME /home/nao

ARG ALDE_CTC_CROSS
ENV ALDE_CTC_CROSS ${ALDE_CTC_CROSS:-${NAO_HOME}/ctc}

ARG KEY_SRV
ENV KEY_SRV ${KEY_SRV:-hkp://keyserver.ubuntu.com:80}
#ENV KEY_SRV ${KEY_SRV:-hkps.pool.sks-keyservers.net}

ARG KEY_UUID
ENV KEY_UUID ${KEY_UUID:-421C365BD9FF1F717815A3895523BAEEB01FA116}

RUN dpkg --add-architecture i386 \
    && apt-get update \
    && apt-get install -y --no-install-recommends locales \
    && locale-gen en_US en_US.UTF-8 \
    && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

ENV LANG en_US.UTF-8

RUN apt-get install -y --no-install-recommends \
        lsb-release \
        software-properties-common \
        apt-transport-https \
    && echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros-latest.list \
    && apt-key adv --keyserver $KEY_SRV --recv-keys $KEY_UUID \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        libc6-i386 \
        apt-transport-https \
        build-essential \
        cmake \
        git \
        libssl-dev \
        wget \
	    unzip \
        zlib1g-dev \
    && apt-get install -y \
        python-rosdep \
        python-rosinstall-generator \
        python-wstool \
        python-rosinstall \
        build-essential \
        python3-vcstool \
        python3-empy

RUN useradd -ms /bin/bash nao
WORKDIR /home/nao
USER nao

ENV CC $ALDE_CTC_CROSS/bin/i686-aldebaran-linux-gnu-cc
ENV CPP $ALDE_CTC_CROSS/bin/i686-aldebaran-linux-gnu-cpp
ENV CXX $ALDE_CTC_CROSS/bin/i686-aldebaran-linux-gnu-c++
ENV RANLIB $ALDE_CTC_CROSS/bin/i686-aldebaran-linux-gnu-ranlib
ENV AR $ALDE_CTC_CROSS/bin/i686-aldebaran-linux-gnu-ar
ENV AAL $ALDE_CTC_CROSS/bin/i686-aldebaran-linux-gnu-aal
ENV LD $ALDE_CTC_CROSS/bin/i686-aldebaran-linux-gnu-ld
ENV READELF $ALDE_CTC_CROSS/bin/i686-aldebaran-linux-gnu-readelf
ENV CFLAGS -isysroot $ALDE_CTC_CROSS/i686-aldebaran-linux-gnu/sysroot
ENV CPPFLAGS -I$ALDE_CTC_CROSS/zlib/include -I$ALDE_CTC_CROSS/bzip2/include -I$ALDE_CTC_CROSS/openssl/include
ENV LDFLAGS -L$ALDE_CTC_CROSS/zlib/lib -L$ALDE_CTC_CROSS/bzip2/lib -L$ALDE_CTC_CROSS/openssl/lib
