#!/bin/bash
set -euf -o pipefail
mkdir -p /home/nao/ros1_dependencies_sources/build/flann
cd /home/nao/ros1_dependencies_sources/build/flann
cmake \
  -DCMAKE_INSTALL_PREFIX=/home/nao/${PEPPER_INSTALL_ROOT}/ros1_dependencies \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_TOOLCHAIN_FILE=/home/nao/pepper_ros1_ws/ctc-cmake-toolchain.cmake \
  -DALDE_CTC_CROSS=/home/nao/ctc \
  -DCMAKE_FIND_ROOT_PATH="/home/nao/ros1_dependencies;/home/nao/ctc" \
  -DBUILD_SHARED_LIBS=ON \
  -DBUILD_TESTS=OFF \
  -DBUILD_PYTHON_BINDINGS=OFF \
  -DBUILD_MATLAB_BINDINGS=OFF \
  -DBUILD_EXAMPLES=OFF \
  ../../src/flann
make -j4 install
