#!/bin/bash
set -euf -o pipefail
mkdir -p /home/nao/ros1_dependencies_sources/build/pcl
cd /home/nao/ros1_dependencies_sources/build/pcl
cmake \
  -DCMAKE_INSTALL_PREFIX=/home/nao/${PEPPER_INSTALL_ROOT}/ros1_dependencies \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_TOOLCHAIN_FILE=/home/nao/pepper_ros1_ws/ctc-cmake-toolchain.cmake \
  -DALDE_CTC_CROSS=/home/nao/ctc \
  -DCMAKE_FIND_ROOT_PATH="/home/nao/${PEPPER_INSTALL_ROOT}/ros1_dependencies;/home/nao/ctc" \
  -DBUILD_SHARED_LIBS=ON \
  -DWITH_VTK=OFF \
  -DWITH_QT=OFF \
  -DWITH_OPENGL=OFF \
  -DBUILD_segmentation=ON \
  -DBUILD_surface=ON \
  -DQHULL_USE_STATIC=OFF \
  -DQHULL_ROOT=/home/nao/${PEPPER_INSTALL_ROOT}/ros1_dependencies/ \
  -DPCL_ENABLE_SSE=OFF \
  -DEIGEN_ROOT=${ALDE_CTC_CROSS}/eigen3 \
  ../../src/pcl
make -j4 install
